"""Add comentario column to InputEvento and DetalleCalculo

Revision ID: 219f304c7ea9
Revises: e8e6bc0b2a1c
Create Date: 2026-06-14 17:49:57.911316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219f304c7ea9'
down_revision: Union[str, Sequence[str], None] = 'e8e6bc0b2a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_calculo', sa.Column('comentario', sa.String(), nullable=True))
    op.add_column('inputs_evento', sa.Column('comentario', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inputs_evento', 'comentario')
    op.drop_column('detalle_calculo', 'comentario')
    # ### end Alembic commands ###
