"""Add comentario column to MovilidadEmpleado

Revision ID: 9bb74db4d75d
Revises: 219f304c7ea9
Create Date: 2026-06-14 18:31:56.565416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb74db4d75d'
down_revision: Union[str, Sequence[str], None] = '219f304c7ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movilidad_empleado', sa.Column('comentario', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movilidad_empleado', 'comentario')
    # ### end Alembic commands ###
