"""Initial migration

Revision ID: d65eb93c1a67
Revises: 
Create Date: 2026-06-11 20:40:07.509812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65eb93c1a67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factores_emision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('subtipo', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('fuente', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('vigencia', sa.String(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factores_emision_id'), 'factores_emision', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contrasena_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('pais', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=False),
    sa.Column('cantidad_asistentes', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('calculo_pendiente', sa.Boolean(), nullable=False),
    sa.Column('public_slug', sa.String(), nullable=True),
    sa.Column('hash_datos', sa.String(), nullable=True),
    sa.Column('hash_resultado', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_id'), 'eventos', ['id'], unique=False)
    op.create_index(op.f('ix_eventos_public_slug'), 'eventos', ['public_slug'], unique=True)
    op.create_table('calculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('es_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculos_evento_id'), 'calculos', ['evento_id'], unique=False)
    op.create_index(op.f('ix_calculos_id'), 'calculos', ['id'], unique=False)
    op.create_table('inputs_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.Column('tipo_fuente', sa.String(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('factor_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('es_actual', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factor_id'], ['factores_emision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inputs_evento_evento_id'), 'inputs_evento', ['evento_id'], unique=False)
    op.create_index(op.f('ix_inputs_evento_factor_id'), 'inputs_evento', ['factor_id'], unique=False)
    op.create_index(op.f('ix_inputs_evento_id'), 'inputs_evento', ['id'], unique=False)
    op.create_table('movilidad_empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transporte', sa.String(), nullable=False),
    sa.Column('distancia', sa.Float(), nullable=False),
    sa.Column('cantidad_empleados', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_fuente', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movilidad_empleado_evento_id'), 'movilidad_empleado', ['evento_id'], unique=False)
    op.create_index(op.f('ix_movilidad_empleado_id'), 'movilidad_empleado', ['id'], unique=False)
    op.create_table('ticket_factor_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('subtipo', sa.String(), nullable=False),
    sa.Column('factor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factor_id'], ['factores_emision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evento_id', 'tipo', 'subtipo', name='uix_evento_tipo_subtipo')
    )
    op.create_index(op.f('ix_ticket_factor_mapping_id'), 'ticket_factor_mapping', ['id'], unique=False)
    op.create_table('tickets_asistentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'evento_id', name='uq_ticket_evento')
    )
    op.create_index(op.f('ix_tickets_asistentes_evento_id'), 'tickets_asistentes', ['evento_id'], unique=False)
    op.create_index(op.f('ix_tickets_asistentes_id'), 'tickets_asistentes', ['id'], unique=False)
    op.create_table('detalle_calculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('subtipo', sa.String(), nullable=True),
    sa.Column('emisiones', sa.Float(), nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=True),
    sa.Column('input_version', sa.Integer(), nullable=True),
    sa.Column('input_valor', sa.Float(), nullable=True),
    sa.Column('input_unidad', sa.String(), nullable=True),
    sa.Column('factor_id', sa.Integer(), nullable=True),
    sa.Column('factor_valor', sa.Float(), nullable=True),
    sa.Column('factor_unidad', sa.String(), nullable=True),
    sa.Column('factor_version', sa.String(), nullable=True),
    sa.Column('factor_fuente', sa.String(), nullable=True),
    sa.Column('cantidad_empleados', sa.Integer(), nullable=True),
    sa.Column('tipo_fuente', sa.String(), nullable=True),
    sa.Column('origen', sa.String(), nullable=True),
    sa.Column('calculo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calculo_id'], ['calculos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_calculo_id'), 'detalle_calculo', ['id'], unique=False)
    op.create_table('evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('calculo_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calculo_id'], ['calculos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencias_calculo_id'), 'evidencias', ['calculo_id'], unique=False)
    op.create_index(op.f('ix_evidencias_evento_id'), 'evidencias', ['evento_id'], unique=False)
    op.create_index(op.f('ix_evidencias_id'), 'evidencias', ['id'], unique=False)
    op.create_table('movilidad_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transporte', sa.String(), nullable=False),
    sa.Column('distancia', sa.Float(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_asistentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movilidad_ticket_id'), 'movilidad_ticket', ['id'], unique=False)
    op.create_index(op.f('ix_movilidad_ticket_ticket_id'), 'movilidad_ticket', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movilidad_ticket_ticket_id'), table_name='movilidad_ticket')
    op.drop_index(op.f('ix_movilidad_ticket_id'), table_name='movilidad_ticket')
    op.drop_table('movilidad_ticket')
    op.drop_index(op.f('ix_evidencias_id'), table_name='evidencias')
    op.drop_index(op.f('ix_evidencias_evento_id'), table_name='evidencias')
    op.drop_index(op.f('ix_evidencias_calculo_id'), table_name='evidencias')
    op.drop_table('evidencias')
    op.drop_index(op.f('ix_detalle_calculo_id'), table_name='detalle_calculo')
    op.drop_table('detalle_calculo')
    op.drop_index(op.f('ix_tickets_asistentes_id'), table_name='tickets_asistentes')
    op.drop_index(op.f('ix_tickets_asistentes_evento_id'), table_name='tickets_asistentes')
    op.drop_table('tickets_asistentes')
    op.drop_index(op.f('ix_ticket_factor_mapping_id'), table_name='ticket_factor_mapping')
    op.drop_table('ticket_factor_mapping')
    op.drop_index(op.f('ix_movilidad_empleado_id'), table_name='movilidad_empleado')
    op.drop_index(op.f('ix_movilidad_empleado_evento_id'), table_name='movilidad_empleado')
    op.drop_table('movilidad_empleado')
    op.drop_index(op.f('ix_inputs_evento_id'), table_name='inputs_evento')
    op.drop_index(op.f('ix_inputs_evento_factor_id'), table_name='inputs_evento')
    op.drop_index(op.f('ix_inputs_evento_evento_id'), table_name='inputs_evento')
    op.drop_table('inputs_evento')
    op.drop_index(op.f('ix_calculos_id'), table_name='calculos')
    op.drop_index(op.f('ix_calculos_evento_id'), table_name='calculos')
    op.drop_table('calculos')
    op.drop_index(op.f('ix_eventos_public_slug'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_id'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_factores_emision_id'), table_name='factores_emision')
    op.drop_table('factores_emision')
    # ### end Alembic commands ###
