"""make_factor_id_nullable

Revision ID: e8e6bc0b2a1c
Revises: d65eb93c1a67
Create Date: 2026-06-11 22:02:48.247567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e6bc0b2a1c'
down_revision: Union[str, Sequence[str], None] = 'd65eb93c1a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_factor_mapping', 'factor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_factor_mapping', 'factor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
